site_name: Arista AVD collection
site_author: Arista Ansible Team
site_description: Arista Validated Design collection's documentation
docs_dir: ansible_collections/arista/avd/
site_favicon: docs/_media/favicon.ico
theme:
  name: material
  features:
    - instant
  font:
    text: Ubuntu
    code: Ubuntu Mono
extra_css:
  - docs/stylesheets/extra.css
copyright: Copyright &copy; 2019 - 2020 Arista Networks
repo_name: Github
repo_url: https://github.com/aristanetworks/ansible-avd
use_directory_urls: true
nav:
  - Installation:
    - Requirements: docs/installation/requirements.md
    - Ansible-galaxy installation: docs/installation/setup-galaxy.md
    - Git installation: docs/installation/setup-git.md
    - Configure development environment: docs/installation/development.md
  - Getting Started: docs/getting-started.md
  - Roles documentation:
    - eos_l3ls_evpn: roles/eos_l3ls_evpn/README.md
    - eos_cli_config_gen: roles/eos_cli_config_gen/README.md
    - cvp_configlet_upload: roles/cvp_configlet_upload/README.md
    - eos_config_deploy_cvp: roles/eos_config_deploy_cvp/README.md
    - eos_config_deploy_eapi: roles/eos_config_deploy_eapi/README.md
    - build_output_folders: roles/build_output_folders/README.md
  - Modules documentation:
    - Module Inventory to containers: docs/modules/inventory_to_container.rst.md
    - Module Configlet Build configuration: docs/modules/configlet_build_config.rst.md
  - About:
    - Contribution Guide: docs/contributing.md
    - Ansible Galaxy page: https://galaxy.ansible.com/arista/cvp
    - Arista CloudVision Modules: https://github.com/aristanetworks/ansible-cvp
    - Arista Automation Examples: https://github.com/aristanetworks/netdevops-examples

markdown_extensions:
  - smarty
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - fontawesome_markdown
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      separator: "-"
      permalink: "#"
      baselevel: 1