---

- name: Generate device configuration in structured format (yaml).
  ansible.builtin.template:
    src: "evpn-fabric-{{ type }}-yml.j2"
    dest: '{{ root_dir }}/intended/structured_configs/{{ inventory_hostname }}.yml'
  delegate_to: localhost
  check_mode: no
  changed_when: False
  tags: [build, provision]

- name: Merge generated device configuration with custom_structured_configuration_ variables (yaml)
  ansible.builtin.template:
    src: base/custom_structured_configuration.j2
    dest: '{{ root_dir }}/intended/structured_configs/{{ inventory_hostname }}.yml'
  delegate_to: localhost
  changed_when: False
  tags: [build, provision]

- name: Include device structured configuration, that was previously generated.
  ansible.builtin.include_vars: '{{ root_dir }}/intended/structured_configs/{{ inventory_hostname }}.yml'
  delegate_to: localhost
  tags: [build, provision]

- name: Generate EVPN fabric documentation in Markdown Format.
  ansible.builtin.template:
    src: documentation/fabric-documentation.j2
    dest: '{{ root_dir }}/documentation/fabric/{{ fabric_name }}-documentation.md'
  delegate_to: localhost
  run_once: true
  check_mode: no
  tags: [build, provision]

- name: Generate Fabric Point-To-Point Links summary in csv format.
  ansible.builtin.template:
    src: documentation/fabric-p2p-links.j2
    dest: '{{ root_dir }}/documentation/fabric/{{ fabric_name }}-p2p-links.csv'
  delegate_to: localhost
  run_once: true
  check_mode: no
  tags: [build, provision]

- name: Generate Fabric Topology in csv format.
  ansible.builtin.template:
    src: documentation/fabric-topology.j2
    dest: '{{ root_dir }}/documentation/fabric/{{ fabric_name }}-topology.csv'
  delegate_to: localhost
  run_once: true
  check_mode: no
  tags: [build, provision]
