name: Ansible Test
on:
  pull_request:
    branches:
      - 'devel'
      - 'releases/**'
    paths:
      - 'ansible_collections/arista/avd/**'
jobs:
  'ansible-test':
    name: Run ansible-test validation
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    env:
      PY_COLORS: 1 # allows molecule colors to be passed to GitHub Actions
      ANSIBLE_FORCE_COLOR: 1 # allows ansible colors to be passed to GitHub Actions
    strategy:
      fail-fast: true
      matrix:
        python_version: [ 3.6 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: update packages
        run: apt-get update

      - name: 'Install sudo'
        run: apt-get -q -y install sudo

      - name: 'Install build essentials'
        run: sudo apt-get install -q -y build-essential

      - name: 'Install requirements'
        run: make github-configure-ci

      - name: 'Install docker'
        run: make install-docker

      - name: 'Install Python requirements'
        run: make install-requirements

      - name: 'ansible-test linting'
        run: make sanity-lint

      - name: 'ansible-test import'
        run: make sanity-import
