name: Auto Assign to Project(s)
on:
  issues:
    types: [opened, reopened]
  pull_request_target:
    types: [opened, reopened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Priority Project
    steps:
    - name: Assign NEW issues and NEW pull requests to priority project
      uses: srggrs/assign-one-project-github-action@1.2.0
      with:
        project: 'https://github.com/aristanetworks/ansible-avd/projects/10'
        column_name: 'Needs triage'
