name: Test Installation
on:
  push:
jobs:
  'setup':
    name: 'One liner installation'
    runs-on: ubuntu-latest
    steps:
      - name: Execute one-liner installation
        run: |
          echo 'Test installation script from: ${GITHUB_REPOSITORY}'
          echo 'Use content from commit: ${GITHUB_SHA}'
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_SHA}/development/install.sh)"
      - name: Run Makefile commands
        run: |
          make
      - name: Start docker shell
        run: |
          make run