name: Code Linting
on: 
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '*'
    paths:
      - 'ansible_collections/arista/avd/**'

jobs:
  'lint-yaml':
    name: Run YAML Linting collection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Lint YAML Content'
        run: |
          sudo apt-get install -y yamllint
          sh .github/lint-yaml
  'lint-python':
    name: Run PYTHON Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Lint Python code in plugins'
        run: |
          pip3 install wheel
          pip3 install pylint
          sh .github/lint-python
