name: Ansible Molecule Latest
on:
  pull_request:
    paths:
      - 'ansible_collections/arista/avd/roles/**'
      - 'ansible_collections/arista/avd/molecules/**'
      - 'development/requirements**'
      - '.github/workflows/molecule_matrix.yml'
    branches:
      - 'releases/*'

jobs:
  molecule_latest:
    name: "Molecule Latest"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python_version: [ 3.6, 3.7, 3.8 ]
        ansible_version: [ '2.9', '2.10' ]
        avd_scenario:
          - 'avd-l3ls-ebgp'
          - 'avd-l3ls-ebgp-json'
          - 'eos-cli-config-gen'
    steps:
      - name: 'set environment variables'
        run: |
          echo "PY_COLORS=1" >> $GITHUB_ENV
          echo "ANSIBLE_FORCE_COLOR=1" >> $GITHUB_ENV

      - uses: actions/checkout@v1

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r development/requirements.txt
          pip install -r development/requirements-dev.txt

      - name: install ansible
        run: |
          pip uninstall -y ansible
          pip install --upgrade ansible==${{ matrix.ansible_version }}
          ansible --version

      - name: Execute molecule
        run: |
          cd ansible_collections/arista/avd
          molecule test --destroy=never  --scenario-name ${{ matrix.avd_scenario }}
          ls -alR molecule
