name: Ansible Execution
on:
  pull_request:
    branches:
      - 'master'
      - 'releases/*'
jobs:
  'Local_Playbook':
    name: Execute Local playbook.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Install requirements'
        run: |
          make github-configure-ci-python3
      - name: Execute testing playbook
        run: |
          cd testing
          ansible-playbook playbook-generate-documentation.yml
      - uses: actions/upload-artifact@v1
        with:
          name: testing-results
          path: testing/
