name: Ansible Execution
on:
  pull_request:
    branches:
      - 'devel'
      - 'releases/*'
jobs:
  'Local_Playbook':
    name: Execute Local playbooks.
    runs-on: ubuntu-latest
    container: avdteam/base:centos-8
    steps:
      - uses: actions/checkout@master

      - name: Execute testing playbook
        run: |
          make playbook-validation

      - uses: actions/upload-artifact@v1
        with:
          name: testing-results
          path: testing/