name: Ansible Execution
on:
  pull_request:
    branches:
      - 'devel'
      - 'master'
      - 'releases/*'
jobs:
  'Local_Playbook':
    name: Execute Local playbook.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python 3 on runner
        uses: actions/setup-python@v1.2.0
        with:
          python-version: '3.x'
      - name: 'Install requirements'
        run: make install-requirements-generic
      - name: Execute testing playbook
        run: |
          make playbook-validation
      - uses: actions/upload-artifact@v1
        with:
          name: testing-results
          path: testing/